version: "3.8"
services:
  broker:
    build: .
    container_name: growatt-rtu-broker
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/log:/var/log
    devices:
      - "/dev/serial/by-path:/dev/serial/by-path"
      # Optional explicit device nodes (uncomment if needed)
      # - "/dev/ttyUSB0:/dev/ttyUSB0"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
    command: >-
      growatt-broker
      --inverter ${INV_DEV}
      --shine ${SHINE_DEV}
      --baud ${BAUD:-9600}
      --bytes ${BYTES:-8E1}
      --tcp ${TCP_BIND:-0.0.0.0:5020}
      --min-period ${MIN_PERIOD:-1.0}
      --rtimeout ${RTIMEOUT:-1.5}
      --log ${LOG_PATH:-/var/log/growatt_broker.jsonl}
