version: "3.8"
services:
  broker:
    build: .
    container_name: growatt-rtu-broker
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - "/dev/serial/by-path:/dev/serial/by-path"
      # Optional explicit device nodes (uncomment if needed)
      # - "/dev/ttyUSB0:/dev/ttyUSB0"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
    command: >-
      growatt-broker
      --inverter ${INV_DEV}
      --shine ${SHINE_DEV}
      --baud ${BAUD:-115200}
      --bytes ${BYTES:-8N1}
      --tcp ${TCP_BIND:-0.0.0.0:5020}
      --tcp-alt ${TCP_ALT_BIND:-0.0.0.0:5021}
      --sniff ${SNIFF_BIND:-0.0.0.0:5700}
      --min-period ${MIN_PERIOD:-1.0}
      --rtimeout ${RTIMEOUT:-1.5}
      --log ${LOG_PATH:--}
